@hostname = http://127.0.0.1
@port = 5000
@host = {{hostname}}:{{port}}
@contentType = application/json

POST  {{hostname}}/chat HTTP/1.1
Content-Type: {{contentType}}

{ "message":"What is your return policy?" }



###
PATCH  {{hostname}}/users/2 HTTP/1.1
Content-Type: {{contentType}}

{
    "username":"john",
    "name": "wick",
    "email": "johnwick@gmail.com",
}

###
DELETE {{hostname}}/users/1 HTTP/1.1

